### ISSUE TITLE
Annotation for cough, suction and PVA ?

### ISSUE THREAD

**Issue by ghost** [hahnicity/ventmode#2]
Hello,

First of all thanks for sharing your work and dataset. It is very valuable. I was just wondering the meaning of some annotations in the folder y_dir. 

Index(['BN', 'vent BN', 'rel time', 'abs time', 'TVi', 'e-time', 'TVe',
       'TVe/TVi ratio', 'PEEP-prev', 'minP', 'PEEP', 'dbl', 'mt', 'bs', 'dtpi',
       'dtpa', 'fa', 'co', 'su', 'vd', 'aNOS', 'wNOS', 'vc', 'pc', 'prvc',
       'ps', 'cpap_sbt', 'other_mode'],
      dtype='object')

What does wNos mean for instance ? 

Also in your paper, you wrote that you got some coughs, suction and PVA. I guess "co" means cough but I was wondering where is the PVA label ? 

Thanks a lot !

LD

**Comment by hahnicity** [comment]
Hi LD,

There is some documentation at the [ventmap repository](www.github.com/hahnicity/ventmap). As for the other annotations I will do what I can


 * aNOS - asynchrony not otherwise specified - its an asynchrony but we dont know which one.
 * wNOS - waveform not otherwise specified. Basically means it looks alright but we have no idea what it is
 * co - cough
 * su - suction
 * dbl - double trigger
 * bs - breath stack
 * mt - multi tigger (kinda like a suction or breath stack)

As for PVAs. We didn't annotate PVAs on this dataset. This dataset was mainly used for annotating ventilator modes. If you want to obtain our PVA dataset, please speak to my PI Jason Adams jyadams@ucdavis.edu. When he gives the OK either him or me will send you that dataset.

**Comment by ghost** [comment]
Ok perfect thanks a lot !
